title: 張志刚的个人博客
author: Zhangzhigang  
email: 15872335542@163.com
description: > # this means to ignore newlines until "baseurl:"
 
# social links
twitter_username: zzgiii  
github_username:  https://github.com/7010G

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
